language: python
python:
- 3.4
- 3.5
- 3.6
install:
- pip install -r requirements.txt
- pip install -r requirements_dev.txt
- pip install .
script:
- pytest
after_success: coveralls
deploy:
  provider: pypi
  user: fooelisa
  password:
    secure: "tP8Wp7pQ+Uzl51/Sd+wKHx6nLoQ+RUPkLWgldlOFBDLqkpcvJavtI0Ic2DLXpLfUYqpo86SHZx5GIktseGL073qrAFOKhnqWg86brp7bP5Ll2jNBCmlz7CF3PndxfgTuH+tSMZbum/nhBAAm0QBe9Brlv6pKi+FLyKPp3Cya1QK92ajsEP90nYRK/imYgs+lfKaVLR/YkfA+L9MrWLYLmpMaoS7fEbJo5LmhN3kRGq4+6Z9WRXpFBxBt40DONzCkOU0W1Fn2J+U2zI6XI8erbCaOMDoh7uiI0a9hvhpOviEjJjdVP0t2fOaIXRemtHrv6gnSiVJ1UT7AyCwnF5ey/2LZcGskc7khk4Qi0P/zPGuowniGy/XfVe1BoOJ48PpRinIgN58aJilSPe18LDHTA/e9Jiw1hGRTvE2PIrLXRhUMQsoD2WoZ3+cH66w11kEBB80KrvjBxsTn3irnY2L+cRBFWw+4nHgZezEBw884k2u3YWwOZLeEm0abVB4y80z/xgUb0rCDCY+rHlhiEdIaYmWzLpSWWjFQgkdbykzE/qwpgnjdICYAL4kTHi2C8JaLpTMBth481WRmQKSX8cLuKSV2d63Yz/cmJjtvS3e7GnArdGztf9PK2JhFArm2Tp1whVZJdPEGzFIBzk14z1XpS6KIuzBFSZI1fbF22XUC/hc="
  on:
    tags: true
    branch: master
