language: python
python:
- 3.4
- 3.5
- 3.6
install:
- pip install -r requirements.txt
- pip install -r requirements_dev.txt
- pip install .
script:
- pytest
after_success: coveralls
deploy:
  provider: pypi
  user: fooelisa
  password:
    secure: a0Jafjgu7Z7NYQOJ7Q7v66Q36DOqX/3qcjxFLYC03wjtlW//3hikhMbY9pFrNKnpe5iTSRd9o3O37wV6lG6n0Oit8isj5ZrUqelLBoerYXA7AmfJN9Gu9hbyawfEH7O81NcGwDtpiGFgPjED+pSW6bJU9H6QuGBeOnaKemQM/u5gsaiOZUO+P2GctZG0LF5fLBnebCaXzI9YM0efJ4VcaMZw3VFvGDKno3cn6+jU6wnENbY6wr+ROX1/yQPOBzuz17KUuSBLRzF/CvwAwx1BNGD26E4x2ChSXfTszNiHEcbpWe5sj1mHsC2ysYnA8q/cAlRYBvTD5w9dMwM8oiE+sQMXyf9u7/6APkfY7u7uZe5pkVV6ZVoOxqRncB9sm86m7R/mCpId+Txhw9390/l9SH8VezXdjvTV9BpJwRkgEvVO6hF+SvXpO1WFpxww+QnA8+yBNetlVGIXMgDCBgkw5dori+Fgr7aESLP0UozcaRdG0jSH8Edt2CREN0z02rkclQd5cskm3jUCxNDRv3XnCOfzexnh23il8gS9xSrAzzknLV9ySxQ1ftJavYOUy2sBXTzSn7gw6t0x2TzF+DAKW+1YlhhHBoBeI3LeIYBn8G0GviArmnpYL2In2ForavJiOJY9relWTXekHMG7feJ+KoLsa6FcVR0wLXf3vZIRUwk=
  on:
    tags: true
    branch: master
