language: python
python:
- 3.4
- 3.5
- 3.6
install:
- pip install -r requirements.txt
- pip install -r requirements_dev.txt
- pip install .
script:
- pytest
after_success: coveralls
deploy:
  provider: pypi
  user: fooelisa
  password:
    secure: XW/XHXcrPMnunSb0XrDNGzDCInrY0JWME8+VDybeiWG3CCxQWAIgIFkzsvXwegUFhT0a+5kx8AWmxvdgbsOIzzvvU6jZsuv0vy93Xl4+cW+xuqn1DL5L5PZmZEMJ/DI+EHNArPdEAm3deSNBIQbBmW9DD7Tc5TX7xDkKqRcVQichqC1/3Fh/tFiSd4wfIBY2QdP0ASRGnd/JBVYEKiZzVlbrXDe+2wLtfDKaG1mGkSiuIE3VRIGpXeDHuCX8GodVxnIprw1Lv9yCuAIcD1k4a6jT5qfymxunRivUJfHMWSBkmcXjwjqJ3teCSbP3zuKR/cT2ymjmgH8+eY+AwYjhVIq/3S7AW7EVja+y7bzsAX6o9upbaRxjoPJiSHCbiF3v9cYW9azknu5xn5FpZVV0ZylO0SerSvkESm7eFUBO3vrKFXpG7sYcj513F3dEqSfrGuGXszsTjPxLPZlBIf1P3viVLGrtBjjEuncDNEjOd9zLRrVq/f3xNEnJi1oXndc95VBGGN46/h1jJjSeCz2pBWEOpi1g6wtUK/KeZkzrX5Hi+QNCkecBTv2T+6PIbgRY1tA/s3a4CHMP8vY4JAoE7HpXGLZ10UMmLtE6RdoLDImBIAgrQwz5OmwavkPPZsxfdcvUSBpgxB3mqzP60N9bWUBUQAPpwFWyIunaO7NPO7k=
  on:
    tags: true
    branch: master
